---
# tasks file for install-compiler-ubuntu
- name: "Update repo for Ubuntu"
  become: true
  apt:
    update_cache: yes
- name: "Install GCC compiler on ubuntu"
  become: true
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - build-essential
      - libssl-dev
      - python-dev
      - libreadline-dev
      - libselinux-dev
      - zlib1g-dev
      - bison
      - flex