---
# tasks file for nginx-centos
- name: "Installation epel-release en pre-requis"
  yum:
    name: epel-release
    state: present
- name: "Installation de nginx"
  yum:
    name: nginx
    state: present
- name: "Insert Index Page"
  template:
    src: index.html
    dest: /usr/share/nginx/html/index.html
- name: "Start nginx"
  service:
    name: nginx
    state: started

